### ISSUE TITLE
The allowed maximum operations in a JSON patch is 10000

### ISSUE THREAD

**Issue by chubchubsancho** [kubescape/storage#116]
:wave: I'm totally new to `kubescape` and found some error during JSON patch for some of our `applicationprofile`

```
{"level":"error","ts":"2024-05-24T08:44:12Z","msg":"tryUpdate func failed","error":"Request entity too large: The allowed maximum operations in a JSON patch is 10000, got 15621","key":"/spdx.softwarecomposition.kubescape.io/applicationprofiles/xxxxx/replicaset-xxxxx-85b8c84dc8"}
```

**storage version**: v0.0.84

**Comment by slashben** [comment]
Hey @chubchubsancho ! We are limiting the size of the profiles to 10k to prevent the overflow of the data pipes on the way (API server and etc.).

We saw in our tests that this was a limit we did not get to. Can you please give more info about your application?

**Comment by chubchubsancho** [comment]
I can see this error for many differents applications i can give you example for public project
* https://github.com/kubernetes/node-problem-detector
```json
{"level":"error","ts":"2024-05-31T07:52:00Z","msg":"tryUpdate func failed","error":"Request entity too large: The allowed maximum operations in a JSON patch is 10000, got 16323","key":"/spdx.softwarecomposition.kubescape.io/applicationprofiles/node-problem-detector/daemonset-node-problem-detector"}
```

**Comment by zhuw726** [comment]
Dear All,

Any update on this topic?

**Comment by slashben** [comment]
> Dear All,
> 
> Any update on this topic?

Hey, we are looking for solution proposals. We must have a hard threshold on maximum number of items. We are looking for user ideas how to set this

**Comment by zhuw726** [comment]
Hey @slashben, thanks for the feedback.

Is it possible to allow users to set the limiting size while acknowledging the risk of overflow?

Or how do to disable this feature? Will it influence anything?

**Comment by matthyx** [comment]
fixed in https://github.com/kubescape/node-agent/pull/331
